name: Model Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check parameter count
      run: |
        python -c "
        from model import CompactMNIST
        from train import count_parameters
        model = CompactMNIST()
        param_count = count_parameters(model)
        assert param_count < 25000, f'Model has {param_count} parameters, exceeding limit of 25,000'
        print(f'✓ Parameter count check passed: {param_count} parameters')
        "
        
    - name: Check training accuracy
      run: |
        python -c "
        from train import train_one_epoch
        accuracy = train_one_epoch()
        assert accuracy > 95, f'Model accuracy {accuracy}% is below required 95%'
        print(f'✓ Accuracy check passed: {accuracy}%')
        "